spring:
  application:
    name: ecommerce-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:ecommerce}
    password: ${DB_PASSWORD:ecommerce}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:xs4FPEf0qOu/5XLNZz/TdsN/sYUsOTgitDKJ6PKM1PM=}
      issuer: ecommerce-api
      audience: ecommerce-client
      access-token-ttl: PT15M
  identity:
    bootstrap-admin:
      email: ${BOOTSTRAP_ADMIN_EMAIL:josue@gmail.com}
      password: ${BOOTSTRAP_ADMIN_PASSWORD:123456789}
  payment:
    fake:
      fail-key: PAYMENT_FAIL
